services:
  - type: web
    name: datapulse-ai
    runtime: python
    pythonVersion: "3.11.9"
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: llama3-8b-8192
      - key: CHROMA_PERSIST_DIRECTORY
        value: ./lancedb_data
      - key: CHROMA_COLLECTION_NAME
        value: datapulse_documents
      - key: RAG_TOP_K
        value: "4"
      - key: CHUNK_SIZE
        value: "500"
      - key: CHUNK_OVERLAP
        value: "50"